version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: laravel11-app
    volumes:
      - .:/var/www
    ports:
      - "8001:8000"
    networks:
      - laravel-network

  mysql:
    image: mysql:8.0
    container_name: laravel11-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - laravel-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel11-phpmyadmin
    restart: always
    ports:
      - "8002:80"
    environment:
      PMA_HOST: laravel11-db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  mysql-data:
